tap "daipeihust/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "asdf"
brew "bat"
brew "exa"
brew "fd"
brew "fzf"
brew "ghq"
brew "git-delta"
brew "htop"
brew "jq"
brew "mas"
brew "mycli"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "zsh-syntax-highlighting"

cask "1password"
cask "adobe-acrobat-reader"
cask "alfred"
cask "clipy"
cask "discord"
cask "docker"
cask "dropbox"
cask "google-chrome"
cask "google-drive"
cask "google-japanese-ime"
cask "honto"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "kindle"
cask "rectangle"
cask "sequel-ace"
cask "slack"
cask "visual-studio-code"
cask "zoom"

mas "Focus To-Do", id: 1258530160
mas "GoodNotes 5", id: 1444383602
mas "LINE", id: 539883307
mas "MenubarX", id: 1575588022
