# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: '!id="$(gh pr list -L100 | fzf | cut -f1)"; [ -n "$id" ] && gh pr checkout "$id"'
    pv: '!id="$(gh pr list -L100 | fzf | cut -f1)"; [ -n "$id" ] && gh pr view "$id" --web'
    pvC: '!id="$(gh pr list --state "closed" -L100 | fzf | cut -f1)"; [ -n "$id" ] && gh pr view "$id" --web'
    pvM: '!id="$(gh pr list --state "merged" -L100 | fzf | cut -f1)"; [ -n "$id" ] && gh pr view "$id" --web'
    iv: '!id="$(gh issue list --state -L100 | fzf | cut -f1)"; [ -n "$id" ] && gh issue view "$id" --web'
    ivC: '!id="$(gh issue list --state "closed" -L100 | fzf | cut -f1)"; [ -n "$id" ] && gh issue view "$id" --web'
    mypr: '!id="$(gh pr list --author "@me" --state "all" -L100 | fzf | cut -f1)"; [ -n "$id" ] && gh pr view "$id" --web'
    prc: pr create --assignee @me --web --title "$1"
    prv: pr view --web "$1"
    isc: issue create --assignee @me --web --title "$1"
    isv: issue view --web "$1"
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
