[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'navarasu/onedark.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/onedark.rc.vim
'''

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'rhysd/clever-f.vim'
hook_add = '''
  source ~/.config/nvim/plugins/clever-f.rc.vim
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  source ~/.config/nvim/plugins/easymotion.rc.vim
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
depends = ['denops.vim']
hook_add = '''
  source ~/.config/nvim/plugins/fuzzy-motion.rc.vim
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
  source ~/.config/nvim/plugins/tcomment.rc.vim
'''

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
hook_add = '''
  source ~/.config/nvim/plugins/nvim-web-devicons.rc.vim
'''

[[plugins]]
repo = 'akinsho/bufferline.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/bufferline.rc.vim
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/lualine.rc.vim
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/gitsigns.rc.vim
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['plenary.nvim']
hook_add = '''
  source ~/.config/nvim/plugins/telescope.rc.vim
'''

[[plugins]]
repo = 'kkharji/sqlite.lua'

[[plugins]]
repo = 'nvim-telescope/telescope-frecency.nvim'
depends = ['sqlite.lua']
hook_add = '''
  source ~/.config/nvim/plugins/telescope-frequency.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons', 'defx-git']
hook_add = '''
  source ~/.config/nvim/plugins/defx.rc.vim
'''

